---
title: "marlin-notebook"
author: "Dan"
date: "6/9/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


# thoughts on movement

Take an SDM. Use some clustering algorithm to break it into centroids... problem there. What if you use habitat a bit more carefully?

Each species has a fixed dispersal range based on its biology. Within that, you use an SDM to scale habitat, and habitat is then used to tune... what? the propostion from each patch that go somewhere, based on say habitat and density? What are you tuning there. Are you maybe making this waaay too complicated? Does scaling by the habitat matrix more or less solve the problem, at least until you start to think about migrations etc? the net probability movign to a cell is a function of its distance and its habitat? so basiaclly you'd only need to tweek the movement rate a bit to get it to work. So, suppose you ahve biomass on the edge of habitat. Some would stay put, none would go to where there is bad habitat, but most would move back towards the good habitat area? 

For migrations / breeding seasons, you could basically just change the habitat layer. interesting. Certainly worth a try to start. For patches where recruitment happens, can also set R0 in proportion to habitat? So total density in a patch would be a function of habitat and R0. 


# structure

this will be centered around two objects. One an object of class "fauna" and another of class "fleet". 

Now, within fauna, should you have slots for individual critters? and then within there slots for each aspect. I like that ida, so you could just pass a fauna object and it would plot all the species in there. Let's just make it a list to start with though

there's problems through and through here. Eigen is much faster for the multiplication, but I can't find any way to get it back into a multidimensional array. armadillo has that through cube, but is substantailly slower. (about 3 times). Not a deal breaker, but annoying. 25 patches squared with 20 age classes for 1000 iterations takes 4.46 seconds with armadillo, 1.5 seconds with eigen. You could keep that down by reducing the max age where possible, and 25 patches sqaured is a lot, and so is 1000 iterations... so maybe not all bad. See if you get a response on eigen by tomorrow, if not, go with armadillo or maybe TMB

Could you write the damn thing in TMB? TMB allows for multidimensional arrays, and does matrix multiplciation, I think with Eigen? Would be pretty damn clunky, wouldn't allow for function syntax, but I suppose you could hide that inside an r function wrapper. 

AHA: 
https://scholar.princeton.edu/sites/default/files/q-aps/files/slides_day4_am.pdf shows how to go back from armadillo to numeric matrix!!!

if all the pop modeling happens in eigen, how much of a speed loss is it to basically just organize things in R, run pop model in cpp
'
