---
title: "fleet-dynamics"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{fleet-dynamics}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(marlin)
```


## Open Access

```{r}
resolution <- 10 # resolution is in squared patches, so 20 implies a 20X20 system, i.e. 400 patches 

years <- 100

seasons <- 1

time_step <- 1 / seasons

steps <- years * seasons

fauna <- 
  list(
    "bigeye" = create_critter(
      common_name = "bigeye tuna",
      adult_diffusion = 10,
      rec_form = 3,
      seasons = seasons,
      fished_depletion = 0.2,
      resolution = resolution,
      steepness = 0.6,
      ssb0 = 1000
    )
  )

# create a fleets object, which is a list of lists (of lists). Each fleet has one element, 
# with lists for each species inside there. Price specifies the price per unit weight of that 
# species for that fleet
# sel_form can be one of logistic or dome


fleets <- list(
  "longline" = create_fleet(
    list("bigeye" = Metier$new(
        critter = fauna$bigeye,
        price = 10,
        sel_form = "logistic",
        sel_start = 1,
        sel_delta = .01,
        catchability = 0,
        p_explt = 2
      )
    ),
    base_effort = resolution ^ 2,
    resolution = resolution,
    responsiveness = .5,
    fleet_model = "open access")
,
"handline" = create_fleet(
  list("bigeye" = Metier$new(
    critter = fauna$bigeye,
    price = 10,
    sel_form = "logistic",
    sel_start = 1,
    sel_delta = .01,
    catchability = 0,
    p_explt = .1
  )
  ),
  base_effort = resolution ^ 2,
  resolution = resolution,
  fleet_model = "constant effort"
))

fleets <- tune_fleets(fauna, fleets, tune_type = "depletion") 


sim <- simmar(fauna = fauna,
                  fleets = fleets,
                  years = years)
proc_sim <- process_marlin(sim)

plot_marlin(proc_sim)

proc_sim$fleets %>% 
  pivot_longer(contains("_effort"), names_to = "fleet2", values_to = "effort") %>% 
  group_by(step, fleet2) %>%
  summarise(effort = sum(effort)) %>% 
  ggplot(aes(step, effort, color = fleet2)) + 
  geom_line()


```

To see the effect of the fleet model choices, let's examine the trajectory of each fleet after the addition of an MPA. 


```{r}

set.seed(42)
#specify some MPA locations
mpa_locations <- expand_grid(x = 1:resolution, y = 1:resolution) %>%
mutate(mpa = x > 4 & y < 6)

mpa_locations %>% 
  ggplot(aes(x,y, fill = mpa)) + 
  geom_tile() + 
  scale_fill_brewer(palette = "Accent", direction  = -1, name = "MPA") + 
  scale_x_continuous(name = "Lat") + 
  scale_y_continuous(name = "Lon")

with_mpa <- simmar(fauna = fauna,
                  fleets = fleets,
                  years = years,
                  mpas = list(locations = mpa_locations,
              mpa_year = floor(years * .5)))

proc_mpa_sim <- process_marlin(with_mpa)

plot_marlin(proc_mpa_sim, plot_var = "c")

plot_marlin(proc_mpa_sim,plot_type = "space")

proc_mpa_sim$fleets %>% 
  pivot_longer(contains("_effort"), names_to = "fleet2", values_to = "effort") %>% 
  group_by(step, fleet2) %>%
  summarise(effort = sum(effort)) %>% 
  ggplot(aes(step, effort, color = fleet2)) + 
  geom_line()


```


