---
title: "habitat"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{habitat}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  message = FALSE,
  warning = FALSE
)
```

## Spawning Aggregation

```{r setup}
library(marlin)

library(dplyr)

library(tidyr)

library(ggplot2)

library(gganimate)

library(ggridges)

years <- 20

resolution <-  10

seasons <- 4

steps <- years * seasons

time_step <-  1 / seasons

land <- expand_grid(x = 1:resolution, y = 1:resolution) %>% 
  filter(between(x,7,10) & between(y, 4,7)) %>% 
  mutate(land = TRUE)


h1 <-  expand_grid(x = 1:resolution, y = 1:resolution) %>%
  mutate(habitat =  dnorm(x, resolution / 2, .025 * resolution) *  dnorm(y, resolution / 2, .025 * resolution)) %>% 
  mutate(habitat = habitat * (x >= 4)) %>% 
    left_join(land, by =c("x","y")) %>% 
    mutate(habitat = ifelse(is.na(land), habitat, NA)) %>% 
    select(-land) 

  

h2 <-  expand_grid(x = 1:resolution, y = 1:resolution) %>%
  mutate(habitat =  -.5 * x + 10) %>% 
  mutate(habitat = habitat * (x < 4)) %>% 
    left_join(land, by =c("x","y")) %>% 
    mutate(habitat = ifelse(is.na(land), habitat, NA)) %>% 
    select(-land) 
  

bigeye_habitat <- h1 %>% 
  pivot_wider(names_from = y, values_from = habitat) %>% 
  select(-x) %>% 
  as.matrix()


huh <- tidyr::pivot_longer(as.data.frame(bigeye_habitat), tidyr::everything())

h1$habitat2 <- as.numeric(huh$value)

bigeye_habitat2 <- h2 %>% 
  pivot_wider(names_from = y, values_from = habitat) %>% 
  select(-x) %>% 
  as.matrix()

bigeye_q <- expand_grid(x = 1:resolution, y = 1:resolution) %>%
  dplyr::mutate(habitat = rlnorm(resolution^2)) %>% 
  pivot_wider(names_from = y, values_from = habitat) %>% 
  select(-x) %>% 
  as.matrix()

# best idea for terrestrial: replace habitat with NAs! then, inside the code, find NAs to find land, and then replace with 0 as habitat values. To work properly though need to enforce habitat being >= 0. 

recruit_habitat <- bigeye_habitat

recruit_habitat[!is.na(recruit_habitat)] <-  1

fauna <- 
  list(
    "bigeye" = create_critter(
      scientific_name = "thunnus obesus",
      base_habitat = list(bigeye_habitat,bigeye_habitat2),
      season_blocks = list(c(1,2),c(3,4)),
      adult_diffusion = list(5, 5), # standard deviation of the number of patches moved by adults
      recruit_diffusion = 10,
      recruit_habitat = recruit_habitat,
      rec_form = 0,
      seasons = seasons,
      init_explt =  1,
      explt_type = "f",
      spawning_seasons = c(1,2),
      sigma_r = .4,
      rec_ac = .2
    )
  )


fleets <- list(
  "longline" = create_fleet(
    list("bigeye" = Metier$new(
      critter = fauna$bigeye,
      price = 10,
      sel_form = "logistic",
      sel_start = 1,
      sel_delta = .01,
      catchability = 1e-3,
      p_explt = 1,
      spatial_catchability = NA
    )
    ),
    base_effort = resolution ^ 2,
    resolution = resolution
  )
)


fleets <- tune_fleets(fauna, fleets) 



sim2 <- simmar(fauna = fauna,
               fleets = fleets,
               years = years)


processed_marlin <- process_marlin(sim = sim2, time_step = time_step)


spawning_agg <- processed_marlin$fauna %>% 
  filter(age == max(age)) %>% 
  group_by(step) %>% 
  mutate(n = n / sum(n)) %>% 
  ungroup() %>% 
  ggplot(aes(x,y,fill = n)) + 
  geom_tile() + 
  transition_time(step) +
  ease_aes('linear') +
  scale_fill_viridis_c(name = "Tunas") + 
  scale_x_continuous(name = "longitude") + 
  scale_y_continuous(name = "latitude")


processed_marlin$fauna %>% 
  group_by(critter, step, age) %>% 
  summarise(numbers = sum(n)) %>% 
  ungroup() %>% 
  filter(age == min(age)) %>% 
  ggplot(aes(step, numbers)) + 
  geom_point()

processed_marlin$fauna %>% 
  group_by(critter, step, age) %>% 
  summarise(numbers = sum(n)) %>% 
  ungroup() %>% 
  filter(step > 10) %>% 
  ggplot(aes(x = age, y = step, height = numbers, group = step)) + 
  geom_density_ridges(stat = 'identity') + 
  facet_wrap(~critter)

animate(spawning_agg, nframes = 100, fps=2)

gganimate::anim_save("spawning_aggregation.gif")


```


## Range Shift

```{r}

# test habitat vector -----------------------------------------------------

shifting_habitat <- vector(mode = "list", length = years)



for (i in 1:years){
  
  shifting_habitat[[i]] <- expand_grid(x = 1:resolution, y = 1:resolution) %>%
    mutate(habitat =  -((y - (1 + i))^2) / 10) %>% 
    left_join(land, by =c("x","y")) %>% 
    mutate(habitat = ifelse(is.na(land), habitat, NA)) %>% 
    select(-land) %>% 
    pivot_wider(names_from = y, values_from = habitat) %>% 
    select(-x) %>% 
    as.matrix()
  
  
}


critter_habitat <- list(bigeye = shifting_habitat)




sim_climate <- simmar(fauna = fauna,
               fleets = fleets,
               habitat = critter_habitat,
               years = years)


processed_marlin <- process_marlin(sim = sim_climate, time_step = time_step, keep_age = FALSE)


range_shift <- processed_marlin$fauna %>% 
  group_by(step) %>% 
  mutate(n = n / max(n)) %>% 
  ungroup() %>% 
  ggplot(aes(x,y,fill = n)) + 
  geom_tile() + 
  transition_time(step) +
  ease_aes('linear') +
  scale_fill_viridis_c(name = "Tunas") + 
  scale_x_continuous(name = "longitude") + 
  scale_y_continuous(name = "latitude")


animate(range_shift, nframes = 100, fps=2)

gganimate::anim_save("range_shift_with_land.gif")

```
