---
title: "Measure MPA Gradients"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{measure_gradients}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}

library(marlin)

library(tidyverse)

theme_set(marlin::theme_marlin())

resolution <- c(5,20) # resolution is in squared patches, so 20 implies a 20X20 system, i.e. 400 patches 

patch_area <- 10

seasons <- 2

years <- 20

tune_type <- "depletion"

steps <- years * seasons

yft_diffusion <- 100
  
yft_depletion <- .2

rec_factor <- 100

mako_depletion <- 0.1

mako_diffusion <- 1

# for now make up some habitat

yft_habitat <- expand_grid(x = 1:resolution[1], y = 1:resolution[2]) %>%
  mutate(habitat =  1,
         habitat = habitat / max(habitat) * yft_diffusion) %>% 
  pivot_wider(names_from = y, values_from = habitat) %>% 
  select(-x) %>% 
  as.matrix()
 

mako_habitat <- expand_grid(x = 1:resolution[1], y = 1:resolution[2]) %>%
  mutate(habitat =  1,
         habitat = habitat / max(habitat) * mako_diffusion) %>% 
  pivot_wider(names_from = y, values_from = habitat) %>% 
  select(-x) %>% 
  as.matrix()


# create a fauna object, which is a list of lists
fauna <- 
  list(
    "Yellowfin Tuna" = create_critter(
      scientific_name = "Thunnus albacares",
      habitat = yft_habitat, # pass habitat as lists
      recruit_habitat = yft_habitat,
      adult_diffusion = yft_diffusion, # cells per year
      recruit_diffusion = rec_factor * yft_diffusion,
      fished_depletion = yft_depletion, # desired equilibrium depletion with fishing (1 = unfished, 0 = extinct),
      density_dependence = "local_habitat", # recruitment form, where 1 implies local recruitment
      seasons = seasons
      ),
    "Shortfin Mako" = create_critter(
      scientific_name = "Isurus oxyrinchus",
      habitat = list(mako_habitat), # pass habitat as lists
      recruit_habitat = mako_habitat,
      adult_diffusion = mako_diffusion,
      recruit_diffusion = rec_factor * mako_diffusion,
      fished_depletion = mako_depletion,
      density_dependence = "local_habitat", # recruitment form, where 1 implies local recruitment
      burn_years = 200,
      seasons = seasons,
      fec_form = "pups",
      pups = 2,
      lorenzen_m = FALSE
    )
  )

fauna$`Shortfin Mako`$plot()

fleets <- list("longline" = create_fleet(list(
  `Yellowfin Tuna` = Metier$new(
    critter = fauna$`Yellowfin Tuna`,
    price = 100, # price per unit weight
    sel_form = "logistic", # selectivity form, one of logistic or dome
    sel_start = .3, # percentage of length at maturity that selectivity starts
    sel_delta = .1, # additional percentage of sel_start where selectivity asymptotes
    catchability = .01, # overwritten by tune_fleet but can be set manually here
    p_explt = 1
    ),
  `Shortfin Mako` = Metier$new(
    critter = fauna$`Shortfin Mako`,
    price = 10,
    sel_form = "logistic",
    sel_start = .1,
    sel_delta = .01,
    catchability = 0,
    p_explt = 1
  )),
  mpa_response = "stay",
  base_effort = prod(resolution),
  spatial_allocation = "rpue",
  resolution = resolution
))

a <- Sys.time()

fleets <- tune_fleets(fauna, fleets, tune_type = tune_type) # tunes the catchability by fleet to achieve target depletion

Sys.time() - a

# run simulations

a <- Sys.time()

nearshore <- simmar(fauna = fauna,
                  fleets = fleets,
                  years = years)

Sys.time() - a
  
proc_nearshore <- process_marlin(nearshore, time_step =  fauna[[1]]$time_step)

plot_marlin(proc_nearshore, max_scale = FALSE)

mpa_locations <- expand_grid(x = 1:resolution[1], y = 1:resolution[2]) |> 
  arrange(x) |> 
  mutate(patch_name = paste(x,y, sep = "_"))


mpas <- mpa_locations$patch_name[1:round(nrow(mpa_locations) * 0.2)]

# mpas <- sample(mpa_locations$patch_name, round(nrow(mpa_locations) * 0.2), replace = FALSE, prob = mpa_locations$x)

mpa_locations$mpa <- mpa_locations$patch_name %in% mpas
  
a <- Sys.time()

nearshore_mpa <- simmar(
  fauna = fauna,
  fleets = fleets,
  years = years,
  manager = list(mpas = list(locations = mpa_locations,
              mpa_year = floor(years * .5)))
)

Sys.time() - a

proc_nearshore_mpa <- process_marlin(nearshore_mpa, time_step =  fauna[[1]]$time_step)

plot_marlin(proc_nearshore_mpa, max_scale = FALSE)

mpa_distances <- get_distance_to_mpas(mpa_locations = mpa_locations, resolution = resolution, patch_area = patch_area)

  mpa_distances |>
    ggplot(aes(x,y,fill = distance_to_mpa_edge)) +
    geom_tile() +
    geom_tile(aes(x,y, color = mpa)) +
    scale_fill_gradient2(low = "darkblue", high = "tomato", mid = "white", midpoint = 0)

  mpa_distances |>
    ggplot(aes(x,y,fill = total_mpa_distance)) +
    geom_tile() +
    geom_tile(aes(x,y, color = mpa))

  
conservation_outcomes <- proc_nearshore_mpa$fauna 
  
fishery_outcomes <- proc_nearshore_mpa$fleets 

conservation_outcomes |>
  filter(step == max(step)) |>
  group_by(step, x, y, patch, critter) |>
  summarise(biomass = sum(b)) |>
  left_join(mpa_distances, by = c("x", "y", "patch")) |>
  ggplot(aes(distance_to_mpa_edge, biomass, color = factor(step))) +
  geom_jitter() +
  facet_wrap( ~ critter, scales = "free_y")

conservation_outcomes |>
  filter(step == max(step)) |>
  group_by(step, x, y, patch, critter) |>
  summarise(biomass = sum(b)) |>
  group_by(critter) |> 
  mutate(biomass = biomass / max(biomass)) |> 
  left_join(mpa_distances, by = c("x", "y", "patch")) |>
  ggplot(aes(x,y, fill = biomass)) +
  geom_tile() +
  facet_wrap( ~ critter, scales = "free_y") + 
  scale_fill_continuous(limits = c(0,1))

fishery_outcomes |> 
  filter(step == max(step), effort > 0) |> 
    left_join(mpa_distances, by = c("x","y","patch")) |> 
  ggplot(aes(distance_to_mpa_edge, effort, color = factor(step))) + 
  geom_point() +
  facet_wrap(~critter, scales = "free_y")


fishery_outcomes |>
  mutate(effort = if_else(effort == 0, NA, effort)) |> 
  filter(step == max(step)) |>
  ggplot(aes(x, y, fill = effort)) +
  geom_tile()



```
