---
title: "seasonal-dynamics"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{seasonal-dynamics}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(marlin)
library(tidyverse)

resolution <- 10 # resolution is in squared patches, so 20 implies a 20X20 system, i.e. 400 patches 

years <- 20

seasons <- 2

time_step <- 1 / seasons

steps <- years * seasons

fauna <- 
  list(
    "bigeye" = create_critter(
      common_name = "bigeye tuna",
      adult_diffusion = 10,
      rec_form = 3,
      seasons = seasons,
      fished_depletion = 0.2,
      resolution = resolution,
      steepness = 0.6,
      ssb0 = 1000,
      spawning_seasons = c(1)
    )
  )

# create a fleets object, which is a list of lists (of lists). Each fleet has one element, 
# with lists for each species inside there. Price specifies the price per unit weight of that 
# species for that fleet
# sel_form can be one of logistic or dome


fleets <- list(
  "longline" = create_fleet(
    list("bigeye" = Metier$new(
        critter = fauna$bigeye,
        price = 10,
        sel_form = "logistic",
        sel_start = 1,
        sel_delta = .01,
        catchability = 0,
        p_explt = 2
      )
    ),
    base_effort = resolution ^ 2,
    resolution = resolution,
    responsiveness = .5,
    cost_per_unit_effort = 1,
    fleet_model = "open access")
,
"handline" = create_fleet(
  list("bigeye" = Metier$new(
    critter = fauna$bigeye,
    price = 10,
    sel_form = "logistic",
    sel_start = 1,
    sel_delta = .01,
    catchability = 0,
    p_explt = 1
  )
  ),
  base_effort = resolution ^ 2,
  resolution = resolution,
  fleet_model = "constant effort"
))

fleets <- tune_fleets(fauna, fleets, tune_type = "depletion") 


sim <- simmar(fauna = fauna,
                  fleets = fleets,
                  years = years)

proc_sim <- process_marlin(sim)

a = proc_sim$fauna %>% 
  filter(age == min(age)) %>% 
  group_by(step) %>% 
  summarise(n = sum(n)) %>% 
  ggplot(aes(step, n)) + 
  geom_point()

plot_marlin(proc_sim, plot_var = "n", max_scale = FALSE)

proc_sim$fleets %>% 
  pivot_longer(contains("_effort"), names_to = "fleet2", values_to = "effort") %>% 
  group_by(step, fleet2) %>%
  summarise(effort = sum(effort)) %>% 
  ggplot(aes(step, effort, color = fleet2)) + 
  geom_line()
```
