# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

sample_problem <- function(x, y) {
    .Call(`_marlin_sample_problem`, x, y)
}

sim_fish_pop <- function(length_at_age, weight_at_age, maturity_at_age, f_p_a, movement, last_n_p_a, patches, burn_steps, steepness, r0, ssb0, m, tune_unfished) {
    .Call(`_marlin_sim_fish_pop`, length_at_age, weight_at_age, maturity_at_age, f_p_a, movement, last_n_p_a, patches, burn_steps, steepness, r0, ssb0, m, tune_unfished)
}

