# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

sample_problem <- function() {
    .Call(`_mar_sample_problem`)
}

fish_model <- function(length_at_age, weight_at_age, maturity_at_age, movement, n_p_a, patches, sim_steps, burn_steps, steepness, r0, m) {
    .Call(`_mar_fish_model`, length_at_age, weight_at_age, maturity_at_age, movement, n_p_a, patches, sim_steps, burn_steps, steepness, r0, m)
}

popmodel <- function(length_at_age, weight_at_age, maturity_at_age, selectivity_at_age, rec_devs, age_vector, sim_years, n_ages, burn_years, rec_form, steepness, r0, m, f) {
    .Call(`_mar_popmodel`, length_at_age, weight_at_age, maturity_at_age, selectivity_at_age, rec_devs, age_vector, sim_years, n_ages, burn_years, rec_form, steepness, r0, m, f)
}

move_matrix_eigen <- function(X, y, its) {
    .Call(`_mar_move_matrix_eigen`, X, y, its)
}

timesTwo <- function(x) {
    .Call(`_mar_timesTwo`, x)
}

